package com.nordgym.constants;

public class GlobalConstants {
    public final static String USER_WITH_SUCH_ID_DOESNT_EXISTS = "Потребител с ID: %s не съществува!";
    public final static String USER_WITH_SUCH_USERNAME_DOESNT_EXISTS = "Потребител с потребителско име: %s не съществува!";
    public final static String SUCH_TRAINING_PROGRAM_DOESNT_EXISTS = "Тренировъчна програма с ID: %s не съществува! ";
    public final static String ERROR = "Грешка %s";
    public final static String SORRY_SOMETHING_WENT_WRONG = "Съжаляваме, нещо се обърка!";
    public final static String SORRY_NO_UPLOADED_RESOURCES_AT_THIS_MOMENT = "Съжаляваме, в момента няма качени ресурси!!";
    public final static String IMAGES_PATH = "D:\\Java Frameworks - Spring\\Project-Nordgym\\nordgymproject\\src\\main\\resources\\static\\images\\";
    public final static String THIS_USERNAME_IS_TAKEN = "Това потребителско име е заето";
    public static final String SUBSCRIPTION_NUMBER_MUST_CONTAINS_ONLY_NUMBERS = "Аб. номер може да съдържа само цифри";
    public static final String THERE_IS_ALREADY_REGISTERED_USER_WITH_THIS_SUBSCRIPTION_NUMBER ="Вече има регистриран потребител с този аб. номер";
    public static final String THIS_FIELD_IS_OBLIGATORY = "Това поле е задължително!";
    public static final String FIRST_NAME_MUST_BEGIN_WITH_CAPITAL_LETTER_AND_CONTAINS_ONLY_LETTERS = "Името трябва да започва с главна и да съдържа само букви";
    public static final String LAST_NAME_MUST_BEGIN_WITH_CAPITAL_LETTER_AND_CONTAINS_ONLY_LETTERS = "Фамилията трябва да започва с главна и да съдържа само букви";
    public static final String PASSWORDS_NOT_EQUALS = "Паролите не съвпадат";
    public static final String YOU_HAVE_ENTERED_INVALID_EMAIL = "Въвели сте невалиден имейл!";
    public static final String WRONG_FORMAT = "Грешен формат!";
    public static final String CANT_BE_LESS_THEN_ONE = "Не може да бъде по-малко от 2";
    public static final String CANT_BE_MORE_THEN_SEVEN = "Не може да бъде повече от 7";
    public static final String CANT_BE_LESS_THEN_FOUR = "Не може да бъде по-малко от 4";
    public static final String CANT_BE_MORE_THEN_TWENTY_FOUR = "Не може да бъде повече от 24";
    public static final String ROOT_ADMIN = "ROOT_ADMIN";
    public static final String USER_NOT_FOUND = "User not found";
    public static final String ADMIN = "ADMIN";
    public static final String SIX_ENTRIES = "SIX_ENTRIES";
    public static final String EIGHT_ENTRIES = "EIGHT_ENTRIES";
    public static final String TWELVE_ENTRIES = "TWELVE_ENTRIES";
    public static final String SIXTEEN_ENTRIES = "SIXTEEN_ENTRIES";
    public static final String TWENTY_FOUR_ENTRIES = "TWENTY_FOUR_ENTRIES";
    public static final String THIRTY_ENTRIES = "THIRTY_ENTRIES";
    public static final String ONE_MONTH = "ONE_MONTH";
    public static final String THREE_MONTHS = "THREE_MONTHS";
    public static final String SIX_MONTHS = "SIX_MONTHS";
    public static final String ONE_YEAR = "ONE_YEAR";
    public static final String USER = "USER";
    public static final String NO_INFO = "No info";
    public static final String USER_ENTRY_WITH_SUCH_ID_DOESNT_EXISTS = "Посещение с ID: %s не съществува!";
}
